project:
  type: book
  output-dir: .

book:
  title: "Measuring Technical Debt in Mission Critical Trading Systems"
  subtitle: "A Service Level Quantitative Framework"
  date: "12 July 2026"
  author:
    name: Tobias Zeier
  abstract: "The abstract will be written at the end of the thesis"
  keyword: "technical debt, technical debt prioritisation, TOPSIS, multi-criteria decision-making, MCDM, trading IT, ITSM, CMDB, DORA metrics, composite score"
  chapters:
    - index.qmd
    - references.qmd
  
  appendices: 
    - appendices/appendixa.qmd
    - appendices/appendixb.qmd
    - appendices/appendixc.qmd

thesis:
  student: 
    id: "12696372"
  supervisor:
    name: "Dr Zahid Ullah"
  co-supervisor:
    name: "Doug Millward"
  degree-name: "Master of Science"
  university: "University of Essex"
  department: "Computing Department"
  group: "Enterprise IT Management Programme"
  declaration: "Frontmatter/declaration.tex"
  acknowledgements: "Frontmatter/acknowledgements.tex"
  abbreviations: "Frontmatter/abbreviations.tex"
  symbols: "Frontmatter/symbols.tex"
  logo: "images/logo.png"
  logo-height: "2.5cm"

keywords:
 - technical debt
 - technical debt prioritisation
 - TOPSIS
 - multi-criteria decision-making
 - MCDM
 - trading IT
 - ITSM
 - CMDB
 - DORA metrics
 - composite score

bibliography: references.bib
csl: harvard-cite-them-right-no-et-al.csl

jupyter: python3

execute:
  echo: false
  warning: false
  message: false
  python: .venv/bin/python3

toclinkcolor: black

format:
  pdf:
    citeproc: false
    filters: 
      - at: pre-quarto
        path: _extensions/andrewheiss/wordcount/citeproc.lua
      - at: pre-quarto
        path: _extensions/andrewheiss/wordcount/wordcount.lua
    documentclass: MastersDoctoralThesis
    classoption: ["12pt", "oneside", "english", "onehalfspacing", "headsepline"]
    mainfont: "Times New Roman"
    fontsize: 12pt
    linestretch: 1.5
    geometry:
      - paper=a4paper
      - inner=2.5cm
      - outer=3.8cm
      - top=2cm
      - bottom=2cm
    template-partials:
      - title.tex
      - before-body.tex
    include-before-body:
      - definitions.tex
    include-in-header:
      - preamble.tex
    code-overflow: wrap
    keep-tex: true
    toc: false
    toc-depth: 2
    number-sections: true
    crossref:
      chapters: true
    top-level-division: chapter
    colorlinks: true
    urlcolor: blue
    linkcolor: black
    citecolor: black

wordcount-pdf: default
wordcount: "Word count: {{< words-body >}}"
